Author::HABTM_Books.create!([
  {author_id: 1, book_id: 1},
  {author_id: 2, book_id: 2},
  {author_id: 3, book_id: 3},
  {author_id: 4, book_id: 4},
  {author_id: 5, book_id: 4},
  {author_id: 6, book_id: 5},
  {author_id: 6, book_id: 6},
  {author_id: 6, book_id: 7},
  {author_id: 7, book_id: 8},
  {author_id: 7, book_id: 9},
  {author_id: 7, book_id: 10},
  {author_id: 8, book_id: 11},
  {author_id: 9, book_id: 11},
  {author_id: 10, book_id: 11},
  {author_id: 9, book_id: 12},
  {author_id: 12, book_id: 13},
  {author_id: 13, book_id: 14},
  {author_id: 14, book_id: 15}
])
Book::HABTM_Categories.create!([
  {book_id: 1, category_id: 1},
  {book_id: 3, category_id: 1},
  {book_id: 4, category_id: 1},
  {book_id: 2, category_id: 1},
  {book_id: 6, category_id: 4},
  {book_id: 7, category_id: 1},
  {book_id: 5, category_id: 1},
  {book_id: 8, category_id: 4},
  {book_id: 9, category_id: 3},
  {book_id: 10, category_id: 4},
  {book_id: 10, category_id: 3},
  {book_id: 11, category_id: 4},
  {book_id: 12, category_id: 4},
  {book_id: 13, category_id: 2},
  {book_id: 14, category_id: 2},
  {book_id: 15, category_id: 2}
])
User.create!([
  {email: "1@mail.com", encrypted_password: "$2a$11$1bGXglsS7ONUoqFYZrdcAORKZIWmXvd7FMVkowhE464NoS5/NTjuO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-07-18 19:05:21", last_sign_in_at: "2017-07-18 19:05:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "user", omniauth_provider: nil, omniauth_uid: nil, image_url: nil},
  {email: "adm2@adm.ua", encrypted_password: "$2a$11$NimRCh2tbqknWp5OqnH8n.9KLxuazEF55ReOSj9vT/Thsd3pBIkVK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, role: "admin", omniauth_provider: nil, omniauth_uid: nil, image_url: nil},
  {email: "ba.artyom@yahoo.com", encrypted_password: "$2a$11$vzww/B3R2tHQsYJcDJELNuegyI5scokiTrLU466B6lV80nNp04pa2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-07-30 12:55:08", last_sign_in_at: "2017-07-30 12:55:08", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "user", omniauth_provider: "facebook", omniauth_uid: "1927728567466043", image_url: "http://graph.facebook.com/v2.6/1927728567466043/picture"},
  {email: "megauser@user.ua", encrypted_password: "$2a$11$N/G8OgNwjx5xLbKUtVEVb.KiZOm4Vxz.n6q4lzgC9TkAb0.Nzsaka", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-09-23 21:52:09", last_sign_in_at: "2017-09-23 21:52:09", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "user", omniauth_provider: nil, omniauth_uid: nil, image_url: nil},
  {email: "adm@adm.ua", encrypted_password: "$2a$11$DSJqBvZzi3aw4pmDeoCJgu54CKrxmDT4joYItLNXY1mvZUWQeMnQW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2017-09-24 10:06:15", last_sign_in_at: "2017-09-23 15:14:04", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "admin", omniauth_provider: nil, omniauth_uid: nil, image_url: nil},
  {email: "user@user.ua", encrypted_password: "$2a$11$NDrHt6cDs34EcWBC/9K3m.LdR2RfjBKhvZu.mWVEFezSWP.M27j5C", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 17, current_sign_in_at: "2017-09-24 10:08:41", last_sign_in_at: "2017-09-24 07:38:25", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", role: "user", omniauth_provider: nil, omniauth_uid: nil, image_url: nil}
])
Order.create!([
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: "R00000093", completed_at: nil, state: "in_progress", user_id: 4, shipping_method_id: 3, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000088", completed_at: "2017-09-20 19:35:00", state: "delivered", user_id: 2, shipping_method_id: 2, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000089", completed_at: nil, state: "in_progress", user_id: 4, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: "R00000083", completed_at: "2017-09-19 18:33:00", state: "delivered", user_id: 2, shipping_method_id: 2, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000084", completed_at: "2017-09-19 18:35:00", state: "delivered", user_id: 2, shipping_method_id: 4, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "", completed_at: nil, state: "in_progress", user_id: 1, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: 2, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000085", completed_at: "2017-09-19 18:37:00", state: "delivered", user_id: 2, shipping_method_id: 3, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: 3, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: 2, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: 2, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: 2, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: nil, completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: 3, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: "R00000080", completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: "R00000081", completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: "R00000082", completed_at: nil, state: "in_progress", user_id: 2, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil},
  {number: "R00000086", completed_at: "2017-09-20 19:30:00", state: "delivered", user_id: 2, shipping_method_id: 4, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000087", completed_at: "2017-09-20 19:32:00", state: "delivered", user_id: 2, shipping_method_id: 3, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000090", completed_at: "2017-09-24 07:39:24", state: "in_queue", user_id: 4, shipping_method_id: 3, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000091", completed_at: "2017-09-24 07:39:57", state: "in_queue", user_id: 4, shipping_method_id: 3, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000092", completed_at: "2017-09-24 07:40:41", state: "in_queue", user_id: 4, shipping_method_id: 4, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000096", completed_at: "2017-09-24 08:03:00", state: "delivered", user_id: 4, shipping_method_id: 4, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000095", completed_at: "2017-09-24 08:01:00", state: "in_delivery", user_id: 4, shipping_method_id: 2, use_billing_address_as_shipping: true, coupon_id: nil},
  {number: "R00000094", completed_at: nil, state: "canceled", user_id: 4, shipping_method_id: nil, use_billing_address_as_shipping: false, coupon_id: nil}
])
Address.create!([
  {type: "ShippingAddress", first_name: "1s", last_name: "", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: nil},
  {type: "BillingAddress", first_name: "1b", last_name: "", address: "", city: "", zip: "", country: "", phone: "", user_id: 1, order_id: nil},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "ShippingAddress", first_name: "11111", last_name: "22222", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 45},
  {type: "BillingAddress", first_name: "tgdjk", last_name: "dgk", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 45},
  {type: "BillingAddress", first_name: "tjsdfh", last_name: "tjk", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 46},
  {type: "BillingAddress", first_name: "dfgj", last_name: "sf", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 47},
  {type: "BillingAddress", first_name: "111", last_name: "222", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 48},
  {type: "ShippingAddress", first_name: "333", last_name: "444", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 48},
  {type: "BillingAddress", first_name: "111", last_name: "444", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 49},
  {type: "ShippingAddress", first_name: "222", last_name: "333", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 49},
  {type: "BillingAddress", first_name: "111", last_name: "222", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 50},
  {type: "ShippingAddress", first_name: "333", last_name: "444", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 50},
  {type: "BillingAddress", first_name: "sdfhasdh", last_name: "fhkdghk", address: "dghkdghkdfgh", city: "dgkdgk", zip: "457", country: "AF", phone: "+32165466874", user_id: nil, order_id: 83},
  {type: "BillingAddress", first_name: "gfhjkxdghk", last_name: "dghkdghkdgh", address: "dghkdghk", city: "dghkdghk", zip: "346", country: "AW", phone: "+3453453", user_id: nil, order_id: 84},
  {type: "BillingAddress", first_name: "dykdykd", last_name: "dgkdghkdghk", address: "ghkdghk", city: "ggdhkjdgk", zip: "457", country: "AW", phone: "+743743732732", user_id: nil, order_id: 85},
  {type: "BillingAddress", first_name: "dgj", last_name: "dgjd", address: "dgjd", city: "dgj", zip: "346", country: "AW", phone: "+32145", user_id: nil, order_id: 86},
  {type: "BillingAddress", first_name: "fjhsfgj", last_name: "fgjdgj", address: "jdg", city: "gjg", zip: "4567", country: "AT", phone: "+4567456", user_id: nil, order_id: 87},
  {type: "ShippingAddress", first_name: "AAAA", last_name: "BBBB", address: "ssss", city: "sfjhsfjh", zip: "78912", country: "AS", phone: "+3564748974", user_id: 4, order_id: nil},
  {type: "BillingAddress", first_name: "FIRSTNAME", last_name: "HGF", address: "asdfh", city: "dfh", zip: "12345", country: "AO", phone: "+33333333", user_id: 4, order_id: nil},
  {type: "BillingAddress", first_name: "sj", last_name: "tjwstyjk", address: "rtjkty", city: "tyjktyjk", zip: "564564", country: "AM", phone: "+3654564", user_id: nil, order_id: 90},
  {type: "BillingAddress", first_name: "dfjtfj", last_name: "srtjstjk", address: "kjhkjh", city: "kljhkljh", zip: "7857856", country: "AQ", phone: "+356464964", user_id: nil, order_id: 91},
  {type: "BillingAddress", first_name: "dhjh", last_name: "sklkj", address: "oljh", city: "ojojh", zip: "86896", country: "AX", phone: "+3654474", user_id: nil, order_id: 92},
  {type: "BillingAddress", first_name: "hjkhjkh", last_name: "ikhhioh", address: "hiohioh", city: "oihiohio", zip: "876876", country: "DZ", phone: "+356464", user_id: nil, order_id: 93},
  {type: "BillingAddress", first_name: "aaa", last_name: "ssss", address: "dddd", city: "ffff", zip: "34", country: "AF", phone: "+64649674", user_id: nil, order_id: 95},
  {type: "ShippingAddress", first_name: "AAAA", last_name: "BBBB", address: "ssss", city: "sfjhsfjh", zip: "11111141", country: "AS", phone: "+3564748974", user_id: nil, order_id: 96},
  {type: "BillingAddress", first_name: "FIRSTNAMEAAAA", last_name: "HGF", address: "11111", city: "ccccvvvvvv", zip: "12345", country: "AF", phone: "+33333333", user_id: nil, order_id: 96}
])
Author.create!([
  {first_name: "Ed", last_name: "Burnette", description: "Ed Burnette is a software industry veteran with more than 30 years of experience as a programmer, author, and analyst. He is a founding member and senior researcher at the SAS Advanced Server Research group, and is the creator of Planet Android (www.planetandroid.com). Ed has authored numerous technical articles and books, including Google Web Toolkit: Taking the Pain out of Ajax and Eclipse IDE Pocket Guide. In his copious spare time, you can often find him playing video games with his two sons at their home in central North Carolina."},
  {first_name: "Chris", last_name: "Griffith", description: "Chris Griffith is the User Experience Lead at a home automation and security company and is also an instructor at the University of California, San Diego Extension, teaching mobile application development. He is also an Adobe Community Professional specializing in PhoneGap/Cordova and Experience Design. Chris is regularly invited to speak at conferences such as Fluent, Adobe MAX and ngConf. He has developed several mobile applications, a variety of code-hinters and ConfiGAP for PhoneGap Build. In addition, he has served as a technical reviewer for several publications and written for uxmag.com. In his spare time, Chris spends time with his family, sea kayaking, hiking, and drinking craft beer with friends. You can follow him on Twitter @chrisgriffith or at chrisgriffith.wordpress.com."},
  {first_name: "Dan", last_name: "Hermes", description: "Dan Hermes is a Xamarin and Microsoft MVP, software consultant, IBM Champion, and founder of Lexicon Systems, an award-winning Xamarin and .NET consulting firm. Mr. Hermes helps developers create great mobile apps and helps businesses develop a winning mobile strategy. His firm's recent Xamarin projects include a cross-platform app for Thermo Fisher Scientific which won a W3, a Davey award, and was a finalist for a Xammy award. Mr. Hermes' clientele includes dozens of software-building firms such as Fidelity Investments, EDS, and Computerworld Magazine. He speaks at conferences and teaches software development at colleges, developer user groups, and corporate training centers. A contemporary Renaissance man, Mr. Hermes is also active in the arts. He is a recognized composer, his classical crossover music having aired on National Public Radio (NPR). He is also an active artist, exhibiting his work internationally, and a founding director of Art Technology New England (ATNE).\r\n\r\nMr. Hermes is the author of a new book entitled Xamarin Mobile Application Development."},
  {first_name: "Jakob", last_name: "Iversen", description: "Jakob Iversen, Ph.D. is Associate Professor of Information Systems, Chair of the Interactive Web Management Program, and Director of Information Technology Services at the University of Wisconsin Oshkosh College of Business. His current research interests include software process improvement, agile software development, e-collaboration, and mobile development. Dr. Iversen teaches and consults on web development, mobile development, technology innovation, information systems management, strategy, and software development processes."},
  {first_name: "Michael", last_name: "Eierman", description: "Michael Eierman, Ph.D is a Professor of Information Systems and Chair of the Information Systems Department at the University of Wisconsin Oshkosh College of Business. Dr. Eierman has worked in the information systems field for nearly 30 years as a programmer, analyst, and consultant, but primarily as a teacher. From the very first class taken in college\r\nat the suggestion of an advisor, information systems have been his passion. His research has taken many directions over his years as a professor but is currently focused on the impact of collaborative and mobile technology. Dr. Eierman is also co-owner and manager of Ei-Sor Development, LLC—a provider of Android and iOS apps designed for the outdoorsman."},
  {first_name: "John", last_name: "Horton", description: "John Horton is a technology enthusiast based in UK. When he is not writing apps, books, or blog articles for Game Code School, he can usually be found playing computer games or indulging in a Nerf war."},
  {first_name: "Jon", last_name: "Duckett", description: "Jon Duckett has been helping companies create innovative digital solutions for over 15 years, designing and delivering web and mobile projects for small businesses and tech startups through to global brands like Diesel, Philips, Nike, Wrangler, and Xerox."},
  {first_name: "Sam", last_name: "Ruby", description: "Sam Ruby has co-chaired the W3C HTML Working Group and has made significant contributions to many of the Apache Software Foundation's open source software projects. He is a Senior Technical Staff Member in the Emerging Technologies Group of IBM."},
  {first_name: "David", last_name: "Copeland", description: "David Bryant Copeland is a programmer and author. He wrote The Senior Software Engineer and Build Awesome Command-Line Applications in Ruby 2, and has been a professional programmer since 1995. He's worked at LivingSocial and Opower, and is the director of engineering at fashion start-up Stitch Fix."},
  {first_name: "Dave", last_name: "Thomas", description: "Dave Thomas is a programmer who likes to evangelize cool stuff. He cowrote \"The Pragmatic Programmer\" and was one of the creators of the Manifesto for Agile Software Development. His book \"Programming Ruby\" introduced the Ruby language to the world, and \"Agile Web Development with Rails\" helped kickstart the Rails revolution."},
  {first_name: "Michael", last_name: "Hartl", description: "Michael Hartl is founder of the educational website LearnEnough.com and author of the Ruby on Rails Tutorial, the leading introduction to web development with Rails. His prior experience includes writing and developing RailsSpace, an extremely obsolete Rails tutorial book, and developing Insoshi, a once-popular and now-obsolete social networking platform in Ruby on Rails. In 2011, Michael received a Ruby Hero Award for his contributions to the Ruby community. He is a graduate of Harvard College, has a Ph.D. in Physics from Caltech, and is an alumnus of the Y Combinator entrepreneur program."},
  {first_name: "Joel", last_name: "Sartore", description: "JOEL SARTORE is a photographer, speaker, author, teacher, and a 25-year contributor to National Geographic magazine as well as Audubon, Geo, Time, Life, Newsweek, and Sports Illustrated. He has written several books including National Geographic's Rare: Portraits of America's Endangered Species, Photographing Your Family, and Let's Be Reasonable, a collection of essays from the CBS Sunday Morning show. Sartore and his work have been the subjects of several national broadcasts, including the National Geographic Channel's Explorer, the NBC Nightly News, NPR's Weekend Edition, and an hour-long PBS documentary, At Close Range. He is also a contributor on the CBS Sunday Morning Show with Charles Osgood. "},
  {first_name: "Peter", last_name: "Stepan", description: "Editor Peter Stepan (Icons of Photography) "},
  {first_name: "Sarah", last_name: "Price", description: "During the early 1700s, the Preiss family arrived in America aboard an old sailing vessel called the Patience. The family left Europe, escaping Catholic persecution for their Anabaptist beliefs. Sarah Price comes from a long line of devout Mennonites, including numerous church leaders and ministers throughout the years. Her involvement with the Amish dates back to 1978. Her writing reflect accurate and authentic stories based upon her own experiences with several Amish communities. \r\n\r\nMs. Price has advanced degrees in Communication (MA), Marketing (MBA), and Educational Leadership (A.B.D.). Ms. Price was a former full-time college professor. After being diagnosed with breast cancer in 2013, she now writes full-time."}
])
Book.create!([
  {title: "Mobile App Development with Ionic 2: Cross-Platform Apps with Ionic, Angular, and Cordova", description: "Learn how to build app store-ready hybrid apps with the Ionic 2, the framework built on top of Apache Cordova (formerly PhoneGap) and Angular. This practical guide shows you how to use Ionic’s tools and services to develop apps with HTML, CSS, and TypeScript, rather than rely on platform-specific solutions found in Android, iOS, and Windows Phone.\r\n\r\nAuthor Chris Griffith takes you step-by-step through Ionic’s powerful collection of UI components, and then helps you use it to build three cross-platform mobile apps. Whether you’re new to this framework or have been working with Ionic 1, this book is ideal for beginning, intermediate, and advanced web developers.\r\n\r\nUnderstand what a hybrid mobile app is, and what comprises a basic Ionic application\r\nLearn how Ionic leverages Apache Cordova, Angular, and TypeScript to create native mobile applications\r\nCreate a Firebase-enabled to-do application that stores data across multiple clients\r\nBuild a tab-based National Park explorer app with Google Map integration\r\nDevelop a weather app with the Darksky weather API and Google’s GeoCode API\r\nDebug and test your app to resolve issues that arise during development\r\nWalk through steps for deploying your app to native app stores\r\nLearn how Ionic can be used to create Progressive Web Apps", price: "49.99", image_url: "https://images-na.ssl-images-amazon.com/images/I/518LpEFWNLL._SX379_BO1,204,203,200_.jpg", publication_year: 2017, dimensions: "H: 9.1'' x W: 6.9'' x D: 0.5'' ", materials: "Paperback"},
  {title: "Xamarin Mobile Application Development: Cross-Platform C# and Xamarin.Forms Fundamentals", description: "Xamarin Mobile Application Development is a hands-on Xamarin.Forms primer and a cross-platform reference for building native Android, iOS, and Windows Phone apps using C# and .NET. This book explains how to use Xamarin.Forms, Xamarin.Android, and Xamarin.iOS to build business apps for your customers and consumer apps for Google Play and the iTunes App Store.\r\n\r\nLearn how to leverage Xamarin.Forms for cross-platform development using the most common UI pages, layouts, views, controls, and design patterns. Combine these with platform-specific UI to craft a visually stunning and highly interactive mobile user experience.\r\n\r\nUse Xamarin.Forms to data bind your UI to both data models and to view models for a Model-View-ViewModel (MVVM) implementation. Use this book to answer the important question: Is Xamarin.Forms right for my project?\r\n\r\nPlatform-specific UI is a key concept in cross-platform development, and Xamarin.Android and Xamarin.iOS are the foundation of the Xamarin platform. Xamarin Mobile Application Development will cover how to build an Android app using Xamarin.Android and an iOS app using Xamarin.iOS while sharing a core code library.\r\n\r\nSQLite is the database-of-choice for many Xamarin developers. This book will explain local data access techniques using SQLite.NET and ADO.NET. Build a mobile data access layer (DAL) using SQLite and weigh your options for web services and enterprise cloud data solutions.\r\n\r\nThis book will show how organize your Xamarin code into a professional-grade application architecture. Explore solution-building techniques from starter-to-enterprise to help you decouple your functional layers, manage your platform-specific code, and share your cross-platform classes for code reuse, testability, and maintainability.\r\n\r\nAlso included are 250+ screenshots on iOS, Android, and Windows Phone and 200+ C# code examples with downloadable C# and XAML versions available from Apress.com.\r\n\r\nThis comprehensive recipe and reference book addresses one of the most important and vexing problems in the software industry today: How do we effectively design and develop cross-platform mobile applications?", price: "49.99", image_url: "https://images-na.ssl-images-amazon.com/images/I/51fHRU5oT%2BL._SX348_BO1,204,203,200_.jpg", publication_year: 2015, dimensions: "H: 10.0\" x W: 7.0\" x D: 1.0\"", materials: "Paperback"},
  {title: "Learning Mobile App Development: A Hands-on Guide to Building Apps with iOS and Android", description: "Now, one book can help you master mobile app development with both market-leading platforms: Apple’s iOS and Google’s Android. Perfect for both students and professionals, Learning Mobile App Development is the only tutorial with complete parallel coverage of both iOS and Android. With this guide, you can master either platform, or both—and gain a deeper understanding of the issues associated with developing mobile apps.\r\n \r\nYou’ll develop an actual working app on both iOS and Android, mastering the entire mobile app development lifecycle, from planning through licensing and distribution.\r\nEach tutorial in this book has been carefully designed to support readers with widely varying backgrounds and has been extensively tested in live developer training courses. If you’re new to iOS, you’ll also find an easy, practical introduction to Objective-C, Apple’s native language.\r\n \r\nAll source code for this book, organized by chapter, is available at https://github.com/LearningMobile/BookApps\r\n \r\nCoverage includes\r\nUnderstanding the unique design challenges associated with mobile apps\r\nSetting up your Android and iOS development environments\r\nMastering Eclipse development tools for Android and Xcode 5 tools for iOS\r\nDesigning interfaces and navigation schemes that leverage each platform’s power\r\nReliably integrating persistent data into your apps\r\nUsing lists (Android) or tables (iOS) to effectively present data to users\r\nCapturing device location, displaying it, and using it in your apps\r\nAccessing hardware devices and sensors\r\nPublishing custom apps internally within an organization\r\nMonetizing your apps on Apple’s AppStore or the Google Play marketplace, as well as other ways of profiting from app development, such as consulting and developer jobs", price: "75.0", image_url: "https://images-na.ssl-images-amazon.com/images/I/51lOFSm9X6L._SX385_BO1,204,203,200_.jpg", publication_year: 2013, dimensions: "H: 9.0 x W: 7.0 x D: 0.9", materials: "Paperback"},
  {title: "Hello, Android: Introducing Google's Mobile Development Platform", description: "Google Android dominates the mobile market, and by targeting Android, your apps can run on most of the phones and tablets in the world. This new fourth edition of the #1 book for learning Android covers all modern Android versions from Android 4.1 through Android 5.0. Freshly added material covers new Android features such as Fragments and Google Play Services. Android is a platform you can't afford not to learn, and this book gets you started.\r\n\r\nAndroid is a software toolkit for mobile phones and tablets, created by Google. It's inside more than a billion devices, making Android the number one platform for application developers. Your own app could be running on all those devices!\r\n\r\nGetting started developing with Android is easy. You don't even need access to an Android phone, just a computer where you can install the Android SDK and the emulator that comes with it. Within minutes, Hello, Android gets you creating your first working application: Android's version of \"Hello, World.\" From there, you'll build up a more substantial example: an Ultimate Tic-Tac-Toe game. By gradually adding features to the game, you'll learn about many aspects of Android programming, such as creating animated user interfaces, playing music and sound effects, building location-based services (including GPS and cell-tower triangulation), and accessing web services. You'll also learn how to publish your applications to the Google Play Store.\r\n\r\nThis fourth edition of the bestselling Android classic has been revised for Android 4.1-4.3 (Jelly Bean), 4.4 (KitKat), and Android 5.0 (Lollipop). Topics have been streamlined and simplified based on reader feedback, and every page and example has been reviewed and updated for compatibility with the latest versions of Android.\r\n\r\nIf you'd rather be coding than reading about coding, this book is for you.", price: "36.0", image_url: "https://images-na.ssl-images-amazon.com/images/I/41522iLnezL._SX415_BO1,204,203,200_.jpg", publication_year: 2015, dimensions: "H: 9.2” x W: 7.5” x D: 0.5”", materials: "Paperback"},
  {title: "Learning Java by Building Android Games - Explore Java Through Mobile Game Development", description: "Android is the fastest growing operating system (OS) with one of the largest installed bases of any mobile OS. Android uses one of the most popular programming languages, Java, as the primary language for building apps of all types. So, you should first obtain a solid grasp of the Java language and its foundation APIs to improve the chances of succeeding as an Android app developer.\r\n\r\nThis book will show you how to get your Android development environment set up and you will soon have your first working game. The difficulty level grows steadily with the introduction of key Java topics such as loops, methods, and OOP. You'll then use them in the development of games. You will learn how to build a math test game, a Simon-like memory game, a retro pong-style game, and for the grand finale, a Snake-style, retro arcade game with real Google Play leaderboards and achievements. The book has a hands-on approach and is packed with screenshots.", price: "31.99", image_url: "https://images-na.ssl-images-amazon.com/images/I/51P4MyHKRlL.jpg", publication_year: 2015, dimensions: "H: 9.2\" x W: 7.5\" x D: 0.9\"", materials: "Paperback"},
  {title: "Building E-commerce sites with VirtueMart Cookbook", description: "This brilliantly accessible book is the perfect introduction to using all the key features of VirtueMart to set up and install a fully-functioning e-commerce store. From the basics to customization, it's simply indispensable.\r\n\r\nOverview\r\n\r\nGet to grips with VirtueMart and build an attractive store powered by Joomla!\r\nIncrease the visibility of your store with SEO and product descriptions\r\nKeep your store profitable by configuring tax, shipping and orders", price: "49.99", image_url: "https://images-na.ssl-images-amazon.com/images/I/51-1Yf-lFEL.jpg", publication_year: 2013, dimensions: "H: 9.2\" x W: 7.5\" x D: 0.7\"", materials: "Paperback"},
  {title: "Android Programming for Beginners", description: "Kick-start your Android programming career, or just have fun publishing apps to the Google Play marketplace\r\nA first-principles introduction to Java, via Android, which means you'll be able to start building your own applications from scratch\r\nLearn by example and build three real-world apps and over 40 mini apps throughout the book", price: "44.99", image_url: "https://images-na.ssl-images-amazon.com/images/I/51-gE8xGFLL.jpg", publication_year: 2015, dimensions: "H: 9.2\" x W: 7.5\" x D: 1.6\"", materials: "Paperback"},
  {title: "JavaScript and JQuery: Interactive Front-End Web Development", description: "In JavaScript & jQuery renowned author Jon Duckett discards the traditional programming book template and approaches writing code in a more relevant, less intimidating way. Full-color and packed with instructional graphics and photos, his books have gained a loyal following by illustrating programming in a way both instructive for newcomers and invaluable for seasoned coders.", price: "25.99", image_url: "https://images-na.ssl-images-amazon.com/images/I/41fqWJ%2Br4gL._SX400_BO1,204,203,200_.jpg", publication_year: 2014, dimensions: "H: 9.3\" x W: 7.5\" x D: 1.6\"", materials: "Hardcover"},
  {title: "Web Design with HTML, CSS, JavaScript and jQuery Set", description: "This two-book set combines the titles HTML & CSS: Designing and Building Web Sites and JavaScript & jQuery: Interactive Front-End Development. Together these two books form an ideal platform for anyone who wants to master HTML and CSS before stepping up to JavaScript and jQuery.\r\n\r\nHTML & CSS covers structure, text, links, images, tables, forms, useful options, adding style with CSS, fonts, colors, thinking in boxes, styling lists and tables, layouts, grids, and even SEO, Google analytics, ftp, and HTML5. JavaScript & jQuery offers an excellent combined introduction to these two technologies using a clear and simple visual approach using diagrams, infographics, and photographs.", price: "47.15", image_url: "https://images-na.ssl-images-amazon.com/images/I/416M8%2B8aNvL._SX435_BO1,204,203,200_.jpg", publication_year: 2014, dimensions: "H: 9.0\" x W: 7.1\" x D: 2.8\"", materials: "Hardcover"},
  {title: "HTML and CSS: Design and Build Websites", description: "Every day, more and more people want to learn some HTML and CSS. Joining the professional web designers and programmers are new audiences who need to know a little bit of code at work (update a content management system or e-commerce store) and those who want to make their personal blogs more attractive. Many books teaching HTML and CSS are dry and only written for those who want to become programmers, which is why this book takes an entirely new approach.", price: "17.32", image_url: "https://images-na.ssl-images-amazon.com/images/I/41R9Qctt%2BbL._SX396_BO1,204,203,200_.jpg", publication_year: 2011, dimensions: "H: 9.0\" x W: 7.1\" x D: 1.1\"", materials: "Paperback"},
  {title: "Agile Web Development with Rails 5.1", description: "Learn Rails the way the Rails core team recommends it, along with the tens of thousands of developers who have used this broad, far-reaching tutorial and reference. If you're new to Rails, you'll get step-by-step guidance. If you're an experienced developer, get the comprehensive, insider information you need for the latest version of Ruby on Rails. The new edition of this award-winning classic is completely updated for Rails 5.1 and Ruby 2.4, with information on system testing, Webpack, and advanced JavaScript.\r\n\r\nRuby on Rails helps you produce high-quality, beautiful-looking web applications quickly---you concentrate on creating the application, and Rails takes care of the details. Rails 5.1 brings many improvements, and this edition is updated to cover the new features and changes in best practices.", price: "57.95", image_url: "https://images-na.ssl-images-amazon.com/images/I/51it%2BfvjxYL._SX415_BO1,204,203,200_.jpg", publication_year: 2017, dimensions: "H: 9.2\" x W: 7.5 x D: 1.4\"", materials: "Paperback"},
  {title: "Rails, Angular, Postgres, and Bootstrap: Powerful, Effective, Efficient, Full-Stack Web Development", description: "Achieve awesome user experiences and performance with simple, maintainable code! Embrace the full stack of web development, from styling with Bootstrap, building an interactive user interface with Angular 4, to storing data quickly and reliably in PostgreSQL. With this fully revised new edition, take a holistic view of full-stack development to create usable, high-performing applications with Rails 5.1.\r\n\r\nRails is a great tool for building web applications, but it's not the best at everything. Embrace the features built into your database. Learn how to use front-end frameworks. Seize the power of the application stack through Angular 4, Bootstrap, and PostgreSQL. When used together, these powerful and easy-to-use tools will open you to a new world of possibilities. This second edition is updated to cover Angular - a completely reworked front-end framework - and dives into new Postgres 9.6 features such as UPSERT. Also new is Webpack coverage, to develop the front-end code for your Rails application.", price: "29.07", image_url: "https://images-na.ssl-images-amazon.com/images/I/51cVFiFfZBL._SX415_BO1,204,203,200_.jpg", publication_year: 2017, dimensions: "H: 9.2\" x W: 7.5\" x D: 0.7\"", materials: "Paperback"},
  {title: "National Geographic The Photo Ark: One Man's Quest to Document the World's Animals", description: "The lush and unique photography in this book represents National Geographic's Photo Ark, a major initiative and lifelong project by photographer Joel Sartore to make portraits of the world's animals—especially those that are endangered. His powerful message, conveyed with humor, compassion, and art: to know these animals is to save them. \r\n\r\nSartore is circling the globe, visiting zoos and wildlife rescue centers to create studio portraits of 12,000 species, with an emphasis on those facing extinction. Wiht a goal of photographing every animal in captivity in the world, he has photographed more than 6,000 already and now, thanks to a multi-year partnership with National Geographic, he may reach his goal. This book showcases his animal portraits: from tiny to mammoth, from the Florida grasshopper sparrow to the greater one-horned rhinoceros. Paired with the eloquent prose of veteran wildlife writer Douglas Chadwick, and an inspiring foreword from Harrison Ford, this book presents a thought-provoking argument for saving all the species of our planet.", price: "35.0", image_url: "https://images-na.ssl-images-amazon.com/images/I/61zqVISlfkL.jpg", publication_year: 2017, dimensions: "H: 10.5\" x W: 10.2\" x D: 1.3\"", materials: "Hardcover"},
  {title: "Photos that Changed the World", description: "Now available in an updated and revised edition, Photos that Changed the World gathers together images of pivotal moments in world history in one stunning volume. In lavish two-page spreads, this book presents nearly one hundred of history’s most memorable photographs — from the Wright Brothers’ first flight to the bombing of Pearl Harbor, from Martin Luther King’s \"I Have a Dream\" speech to Nelson Mandela’s release from prison, and from the inauguration of President Barack Obama to the Syrian refugee crisis. The volume features pictures from photography masters such as Lewis Hine, Dorothea Lange, Yousuf Karsh, Diane Arbus, and James Nachtwey, as well as iconic images from lesser-known and unknown photojournalists. Photos that Changed the World has been updated to include indelible images of the most significant recent events. Engaging essays accompany each photograph and tell the story behind each image.", price: "19.95", image_url: "https://images-na.ssl-images-amazon.com/images/I/517JAFQLpdL.jpg", publication_year: 2016, dimensions: "H: 9.5\" x W: 7.8\" x D: 0.8\"", materials: "Paperback"},
  {title: "The Faded Photo", description: "Some things should be kept private. Frances Snyder can never quite get her mother’s voice out of her head—how to be the perfect wife, the perfect mother. Frances’s home life is demanding, and while she’s busy seeing to everyone else’s needs, Frances doesn’t have the luxury of spare time.\r\n\r\nSo when she is diagnosed with breast cancer, she thinks that she can handle it on her own. Dealing with endless tests, brutal chemotherapy, and the looming specter of surgery, Frances chooses to face cancer on her own terms: alone. That is, until she finally understands that unexpected friendship—and unconditional love—can offer hope in the darkest hours.\r\n\r\nWith tenderness, grace, and flashes of humor, bestselling author Sarah Price draws upon her own experience as a breast cancer survivor to create a story about one woman’s determined and solitary journey into the unknown—in hopes that she’ll find her way back home.", price: "12.95", image_url: "https://images-na.ssl-images-amazon.com/images/I/51uYi-7EOYL.jpg", publication_year: 2017, dimensions: "H: 8.2\" x W: 5.5\" x D: 1.0\"", materials: "Paperback"}
])
Cart.create!([
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil},
  {coupon_id: nil}
])
LineItem.create!([
  {book_id: 15, cart_id: 4, quantity: 1, order_id: nil, price: nil},
  {book_id: 15, cart_id: 4, quantity: 1, order_id: nil, price: nil},
  {book_id: 15, cart_id: 4, quantity: 1, order_id: nil, price: nil},
  {book_id: 15, cart_id: 4, quantity: 1, order_id: nil, price: nil},
  {book_id: 15, cart_id: 4, quantity: 1, order_id: nil, price: nil},
  {book_id: 15, cart_id: 4, quantity: 1, order_id: nil, price: nil},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: nil, price: nil},
  {book_id: 11, cart_id: nil, quantity: 25, order_id: 86, price: "57.95"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 92, price: "12.95"},
  {book_id: 2, cart_id: nil, quantity: 3, order_id: 7, price: nil},
  {book_id: 3, cart_id: nil, quantity: 2, order_id: 7, price: nil},
  {book_id: 4, cart_id: nil, quantity: 1, order_id: 7, price: nil},
  {book_id: 9, cart_id: nil, quantity: 20, order_id: 87, price: "47.15"},
  {book_id: 2, cart_id: nil, quantity: 20, order_id: 45, price: "49.99"},
  {book_id: 14, cart_id: nil, quantity: 1, order_id: 17, price: nil},
  {book_id: 9, cart_id: nil, quantity: 1, order_id: 17, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 46, price: "49.99"},
  {book_id: 2, cart_id: nil, quantity: 3, order_id: 37, price: nil},
  {book_id: 11, cart_id: nil, quantity: 2, order_id: 37, price: nil},
  {book_id: 13, cart_id: nil, quantity: 1, order_id: 18, price: nil},
  {book_id: 12, cart_id: nil, quantity: 1, order_id: 18, price: nil},
  {book_id: 15, cart_id: nil, quantity: 3, order_id: 18, price: nil},
  {book_id: 14, cart_id: nil, quantity: 2, order_id: 18, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 47, price: "49.99"},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 48, price: "49.99"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 19, price: nil},
  {book_id: 14, cart_id: nil, quantity: 1, order_id: 19, price: nil},
  {book_id: 13, cart_id: nil, quantity: 1, order_id: 19, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 49, price: "49.99"},
  {book_id: 10, cart_id: nil, quantity: 1, order_id: 20, price: nil},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 20, price: nil},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: 50, price: "57.95"},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 38, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 39, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 40, price: nil},
  {book_id: 13, cart_id: nil, quantity: 1, order_id: 21, price: nil},
  {book_id: 12, cart_id: nil, quantity: 1, order_id: 21, price: nil},
  {book_id: 14, cart_id: nil, quantity: 6, order_id: 21, price: nil},
  {book_id: 2, cart_id: nil, quantity: 2, order_id: 44, price: "49.99"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 22, price: nil},
  {book_id: 11, cart_id: nil, quantity: 3, order_id: 80, price: "57.95"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 23, price: nil},
  {book_id: 14, cart_id: nil, quantity: 2, order_id: 23, price: nil},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: nil, price: nil},
  {book_id: 3, cart_id: nil, quantity: 1, order_id: nil, price: nil},
  {book_id: 13, cart_id: nil, quantity: 1, order_id: 23, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 41, price: nil},
  {book_id: 4, cart_id: nil, quantity: 1, order_id: 24, price: nil},
  {book_id: 2, cart_id: nil, quantity: 2, order_id: 24, price: nil},
  {book_id: 4, cart_id: nil, quantity: 1, order_id: 25, price: nil},
  {book_id: 14, cart_id: nil, quantity: 1, order_id: 26, price: nil},
  {book_id: 15, cart_id: nil, quantity: 3, order_id: 81, price: "12.95"},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: 27, price: nil},
  {book_id: 14, cart_id: nil, quantity: 1, order_id: 81, price: "19.95"},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: 28, price: nil},
  {book_id: 3, cart_id: nil, quantity: 1, order_id: 28, price: nil},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: 29, price: nil},
  {book_id: 12, cart_id: nil, quantity: 10, order_id: 84, price: "29.07"},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 30, price: nil},
  {book_id: 14, cart_id: nil, quantity: 1, order_id: 31, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 32, price: nil},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 82, price: "12.95"},
  {book_id: 13, cart_id: nil, quantity: 1, order_id: 33, price: nil},
  {book_id: 13, cart_id: nil, quantity: 4, order_id: 82, price: "35.0"},
  {book_id: 3, cart_id: nil, quantity: 1, order_id: 34, price: nil},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 35, price: nil},
  {book_id: 11, cart_id: nil, quantity: 1, order_id: 36, price: nil},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 83, price: "12.95"},
  {book_id: 12, cart_id: nil, quantity: 1, order_id: 93, price: "29.07"},
  {book_id: 3, cart_id: nil, quantity: 20, order_id: 88, price: "49.99"},
  {book_id: 2, cart_id: nil, quantity: 1, order_id: 42, price: nil},
  {book_id: 8, cart_id: nil, quantity: 1, order_id: 93, price: "25.99"},
  {book_id: 3, cart_id: nil, quantity: 1, order_id: 43, price: nil},
  {book_id: 15, cart_id: nil, quantity: 2, order_id: 85, price: "12.95"},
  {book_id: 14, cart_id: nil, quantity: 2, order_id: 85, price: "19.95"},
  {book_id: 13, cart_id: nil, quantity: 3, order_id: 85, price: "35.0"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 94, price: "12.95"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 95, price: "12.95"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 89, price: "12.95"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 90, price: "12.95"},
  {book_id: 13, cart_id: nil, quantity: 1, order_id: 91, price: "35.0"},
  {book_id: 15, cart_id: nil, quantity: 1, order_id: 96, price: "12.95"},
  {book_id: 15, cart_id: 114, quantity: 1, order_id: nil, price: "12.95"}
])
Review.create!([
  {title: "fs", text: "a-zA-Z0-9o,,,,, roneof!# $%&'*+-/=?^_`{|}~.", score: 3, status: "unprocessed", book_id: 15, user_id: 1},
  {title: "!?/", text: "dsfg", score: 4, status: "unprocessed", book_id: 15, user_id: 1},
  {title: "New review", text: "55555", score: 5, status: "unprocessed", book_id: 15, user_id: 2},
  {title: "4threview ", text: "Got 1 score", score: nil, status: "unprocessed", book_id: 15, user_id: 1},
  {title: "123", text: "last review for this book I believe", score: 3, status: "rejected", book_id: 15, user_id: 1},
  {title: "4threview ", text: "Got 1 score", score: 1, status: "approved", book_id: 15, user_id: 1},
  {title: "4threview ", text: "Got 1 score", score: 1, status: "rejected", book_id: 15, user_id: 1},
  {title: "2", text: "22", score: 2, status: "unprocessed", book_id: 15, user_id: 2},
  {title: "3", text: "333", score: 3, status: "unprocessed", book_id: 15, user_id: 2},
  {title: "ghmk", text: "dghmkdgmk", score: nil, status: "unprocessed", book_id: 15, user_id: 4}
])
ShippingMethod.create!([
  {name: "Delivery Next Day!", days_min: 3, days_max: 7, price: 5.0},
  {name: "Pick Up In-Store", days_min: 5, days_max: 20, price: 10.0},
  {name: "Expressit", days_min: 2, days_max: 3, price: 15.0}
])
Category.create!([
  {name: "Mobile development"},
  {name: "Photo"},
  {name: "Web design"},
  {name: "Web development"}
])
Coupon.create!([
  {code: "12345678", discount: "20.0", valid_until: "2017-12-31"}
])
BillingAddress.create!([
  {type: "BillingAddress", first_name: "1b", last_name: "", address: "", city: "", zip: "", country: "", phone: "", user_id: 1, order_id: nil},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tfh", last_name: "fsdghsfh", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 42},
  {type: "BillingAddress", first_name: "tgdjk", last_name: "dgk", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 45},
  {type: "BillingAddress", first_name: "tjsdfh", last_name: "tjk", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 46},
  {type: "BillingAddress", first_name: "dfgj", last_name: "sf", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 47},
  {type: "BillingAddress", first_name: "111", last_name: "222", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 48},
  {type: "BillingAddress", first_name: "111", last_name: "444", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 49},
  {type: "BillingAddress", first_name: "111", last_name: "222", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 50},
  {type: "BillingAddress", first_name: "sdfhasdh", last_name: "fhkdghk", address: "dghkdghkdfgh", city: "dgkdgk", zip: "457", country: "AF", phone: "+32165466874", user_id: nil, order_id: 83},
  {type: "BillingAddress", first_name: "gfhjkxdghk", last_name: "dghkdghkdgh", address: "dghkdghk", city: "dghkdghk", zip: "346", country: "AW", phone: "+3453453", user_id: nil, order_id: 84},
  {type: "BillingAddress", first_name: "dykdykd", last_name: "dgkdghkdghk", address: "ghkdghk", city: "ggdhkjdgk", zip: "457", country: "AW", phone: "+743743732732", user_id: nil, order_id: 85},
  {type: "BillingAddress", first_name: "dgj", last_name: "dgjd", address: "dgjd", city: "dgj", zip: "346", country: "AW", phone: "+32145", user_id: nil, order_id: 86},
  {type: "BillingAddress", first_name: "fjhsfgj", last_name: "fgjdgj", address: "jdg", city: "gjg", zip: "4567", country: "AT", phone: "+4567456", user_id: nil, order_id: 87},
  {type: "BillingAddress", first_name: "FIRSTNAME", last_name: "HGF", address: "asdfh", city: "dfh", zip: "12345", country: "AO", phone: "+33333333", user_id: 4, order_id: nil},
  {type: "BillingAddress", first_name: "sj", last_name: "tjwstyjk", address: "rtjkty", city: "tyjktyjk", zip: "564564", country: "AM", phone: "+3654564", user_id: nil, order_id: 90},
  {type: "BillingAddress", first_name: "dfjtfj", last_name: "srtjstjk", address: "kjhkjh", city: "kljhkljh", zip: "7857856", country: "AQ", phone: "+356464964", user_id: nil, order_id: 91},
  {type: "BillingAddress", first_name: "dhjh", last_name: "sklkj", address: "oljh", city: "ojojh", zip: "86896", country: "AX", phone: "+3654474", user_id: nil, order_id: 92},
  {type: "BillingAddress", first_name: "hjkhjkh", last_name: "ikhhioh", address: "hiohioh", city: "oihiohio", zip: "876876", country: "DZ", phone: "+356464", user_id: nil, order_id: 93},
  {type: "BillingAddress", first_name: "aaa", last_name: "ssss", address: "dddd", city: "ffff", zip: "34", country: "AF", phone: "+64649674", user_id: nil, order_id: 95},
  {type: "BillingAddress", first_name: "FIRSTNAMEAAAA", last_name: "HGF", address: "11111", city: "ccccvvvvvv", zip: "12345", country: "AF", phone: "+33333333", user_id: nil, order_id: 96}
])
ShippingAddress.create!([
  {type: "ShippingAddress", first_name: "1s", last_name: "", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: nil},
  {type: "ShippingAddress", first_name: "11111", last_name: "22222", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 45},
  {type: "ShippingAddress", first_name: "333", last_name: "444", address: "", city: "", zip: "", country: "", phone: "", user_id: nil, order_id: 48},
  {type: "ShippingAddress", first_name: "222", last_name: "333", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 49},
  {type: "ShippingAddress", first_name: "333", last_name: "444", address: "", city: "", zip: "", country: "AF", phone: "", user_id: nil, order_id: 50},
  {type: "ShippingAddress", first_name: "AAAA", last_name: "BBBB", address: "ssss", city: "sfjhsfjh", zip: "78912", country: "AS", phone: "+3564748974", user_id: 4, order_id: nil},
  {type: "ShippingAddress", first_name: "AAAA", last_name: "BBBB", address: "ssss", city: "sfjhsfjh", zip: "11111141", country: "AS", phone: "+3564748974", user_id: nil, order_id: 96}
])
